language: node_js
node_js:
    - '14' # EOL: April 2023
    - '12' # EOL: April 2022
    - '10' # EOL: April 2021

jobs:
    include:
        - stage: deploy
          node_js: "lts/*"
          script: skip
          before_deploy:
              - if [ "$TRAVIS_BRANCH" = master ] && [ "$TRAVIS_PULL_REQUEST" = false ]; then npm version prerelease --no-git-tag-version --preid "$TRAVIS_BUILD_NUMBER"; fi
          deploy:
              - provider: npm
                email: info@saturnserver.org
                api_key:
                    secure: uth84JCOZIzNg3JsQDNIDjnOh//NHV9SPlRwkZjNoTZPQ6ai2K5UQ/WuDtag1ve79B9d4jcRZmKOMmMRBewYmFH4rTp4A0TGMRYLYDGvYU4pSuGr0cfh2RqhEXE5tqJL8tPDfWYyOoAxnk5vFOXeFEsKGw106T/Sq3RXG57AwjpdEO17zc+bqzNxKdZ7EPy/lLx6WwRyRWfr2EkDA+zquZqEIbP7jskexHUw0WSy1LIwa7zrfM0r8Vk2m1DdMDAta7CYfeswsYCcQjIauRU5KyKNVwE5Mp7RF3R5tnXNUA6aL8JTSETN/CvzNb4P4u+31VvMa+CkaRM3dfj8bYINtfNa2bUA1NHaJVQcUF0YtoC26bq2yvXyzkqvCelXQ4s5QCmwtJGjQqcC3a73MzLvRZamGJcxu/n3nxlcuskPTFa6Cij1kv6I+2NDa3p35328ReSbuVJyc8oehZKppwkZQIxHRTdCHuzSmIw37ONpSfAl9jKbY+/qT95DA/mGTDqLHtqxuKbixsgiSbWtOorMPaBrsxC1t3hLOfmqv5G1Z8fxMr91/uGcwhDeedpek+n4EUIlOXywq06gG4sVvuWxJwq1LSzMtfXkBs4T4E0evprhYRNXGuEiP+YXNiZj2bpXqE35SXUHQRbbfYdLSO0PwngcQ1EmJH/WQ2PDdPlYZZU=
                tag: next
                skip_cleanup: true
                on:
                    branch: master
                    repo: Ionaru/random-string
              - provider: npm
                email: info@saturnserver.org
                api_key:
                    secure: uth84JCOZIzNg3JsQDNIDjnOh//NHV9SPlRwkZjNoTZPQ6ai2K5UQ/WuDtag1ve79B9d4jcRZmKOMmMRBewYmFH4rTp4A0TGMRYLYDGvYU4pSuGr0cfh2RqhEXE5tqJL8tPDfWYyOoAxnk5vFOXeFEsKGw106T/Sq3RXG57AwjpdEO17zc+bqzNxKdZ7EPy/lLx6WwRyRWfr2EkDA+zquZqEIbP7jskexHUw0WSy1LIwa7zrfM0r8Vk2m1DdMDAta7CYfeswsYCcQjIauRU5KyKNVwE5Mp7RF3R5tnXNUA6aL8JTSETN/CvzNb4P4u+31VvMa+CkaRM3dfj8bYINtfNa2bUA1NHaJVQcUF0YtoC26bq2yvXyzkqvCelXQ4s5QCmwtJGjQqcC3a73MzLvRZamGJcxu/n3nxlcuskPTFa6Cij1kv6I+2NDa3p35328ReSbuVJyc8oehZKppwkZQIxHRTdCHuzSmIw37ONpSfAl9jKbY+/qT95DA/mGTDqLHtqxuKbixsgiSbWtOorMPaBrsxC1t3hLOfmqv5G1Z8fxMr91/uGcwhDeedpek+n4EUIlOXywq06gG4sVvuWxJwq1LSzMtfXkBs4T4E0evprhYRNXGuEiP+YXNiZj2bpXqE35SXUHQRbbfYdLSO0PwngcQ1EmJH/WQ2PDdPlYZZU=
                skip_cleanup: true
                on:
                    branch: master
                    tags: true
                    repo: Ionaru/random-string
